# Counting DNA Nucleotides


# Counts nucleotide occurenence in a sequence
def countNucFrequency(seq):
    tmpFreqDict = {"A": 0, "C": 0, "G": 0, "T": 0}
    for nuc in seq:
        tmpFreqDict[nuc] += 1
    return tmpFreqDict
    # return dict(collections.Counter(seq))


DNAStr = "ACTTTGCCGCGAGAATGTCGGCTGAATCAGCAATGAAGGGTTGCAAAGCCGTTTATCCACTTGGACTACGATCCAAATGCGATTCCCGGCCGAATGCAAGCCTG" \
         "GAGCCTCAAGACCAGTCTTTTGATCCCCACGACCAGAAGGAACATATGTGTCTGGTTCAAGAAACTATTGACTACTTTAAGCCTACCACGCAAATGGTACGGAA" \
         "CCACAGTGTCCCACGTAACTGGCGGTCAAATACAACAATGTATTCCTTAGAGATGATACCGTCGCGATGGGTCTAGCAGTACAGTTCTCTAGTTCAGGTAGGTT" \
         "TAGGCATACCTTTTAATAATTTTGAATGACGTGCTCGCTGAGGCACATGCACGTTCTCGGGCAGGTCAGCTGCCTAACGGTGGCTGCGAAGATTCATAGTGCCG" \
         "CCCAGGATAAATTGTCCAGAGACCTGTGCTGGGACCTTGCTGGGACACACACCCCAAGCGGCTAAATACAGTCCTTCACTTATCACTGGAAGCGGAATACGCCC" \
         "GATGTTATGCAATGGACGTCGCCGAGCCTTAGGGCGATCCGATAACCTGAGCCCTACTAGGTCCCTACGCGGCATCTGGGCCACTCTCAAGGTCCTCACCCGGT" \
         "ACTAGTAGCTATTCGAAGTCCATTTGAACAAATTAACCAAATAGTCCTCCATTTCTGCCAACCGTTGGCCAGAAGATAATGATGGGGACGAGGAAAAACGCGGG" \
         "CGAATGCGTACTTGTCAGAGCCGTCCTATAACATAGCGTTGGATAATGAAGGTTTAGTCTCCATTGTCCTTCAACGTTGCCTTCATCGTACTTACGATGAGAGC" \
         "CACCAAGATTCTGTCTACTCAGCGTGGTCTTCAAAGATTTACCGGACAGTATTGCCTGGCTTCGACACAATGCGATCTTGGAG"
result = countNucFrequency(DNAStr)
print(" ".join([str(val) for key, val in result.items()]))
